### ISSUE TITLE
Missing triggerClass pass-through property

### ISSUE THREAD

**Issue by pkvince** [RyanNerd/ember-power-timepicker#2]
Hi!

First of all, thank you for creating this addon, I just needed a neat and simple timepicker and stumbled upon yours! Works great!

Ember-power-select has a `triggerClass` property that can be used to apply a class to the trigger only, and it's really useful (for applying let's say a background icon on the trigger).

It would be great to have the ability to do so with your timepicker.

Let me know if you think it's a good idea!

Thank you!

**Comment by RyanNerd** [comment]
I'll see if I can add this today. Good catch.
